x-generic-node: &generic-node
  image: tharsishq/evmos:v20.0.0
  volumes:
    - ./data/chain:/data
    - ./entrypoints/node.sh:/entrypoint.sh
    - ./genesis.json:/genesis.json
  entrypoint: /entrypoint.sh

services:
  node-a:
    <<: *generic-node
    ports:
      - 8545:8545
      - 26656:26656
      - 26660:26660
    command: --home /data/node-a start --chain-id $CHAIN_ID
  node-b:
    <<: *generic-node
    command: --home /data/node-b start --chain-id $CHAIN_ID
    depends_on:
      - node-a
    ports:
      - 26657:26656
      - 26661:26660
  node-c:
    <<: *generic-node
    command: --home /data/node-c start --chain-id $CHAIN_ID
    depends_on:
      - node-a
    ports:
      - 26658:26656
      - 26662:26660
  node-d:
    <<: *generic-node
    command: --home /data/node-d start --chain-id $CHAIN_ID
    depends_on:
      - node-a
    ports:
      - 26659:26656
      - 26663:26660
